# aws
repos:
# cfn-lint
-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.54.1  # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        files: templates/.*\.(json|yml|yaml)$
